services:
  - type: web
    name: pawstagram
    env: node
    region: oregon
    plan: free
    buildCommand: npm run build
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/auth/me
